// tools/mon.ts — the Pocket Mon command (docs/MON.md).
//
//   bun tools/mon.ts cook             cook apps/mon into dist/sparkwood.monpak
//   bun tools/mon.ts sim [args…]      cook, then run the headless simulator
//   bun tools/mon.ts check            cook + run the story tape against goldens
//   bun tools/mon.ts record           cook + re-record the golden hashes
//   bun tools/mon.ts shots [dir]      cook + write a PNG per checkpoint
//   bun tools/mon.ts psp [cargo args] cook, then build the PSP EBOOT
//   bun tools/mon.ts run              …and launch it in PPSSPP
//
// The pak is cooked first by every subcommand on purpose: content lives in
// TypeScript, and a stale pak is the one failure that looks like an engine bug
// (see the repo-wide "stale dist is target-flavored" lesson).

import { $ } from "bun";
import { existsSync, mkdirSync } from "node:fs";
import { resolvePspBuildToolchain } from "./psp-toolchain.ts";

const root = new URL("..", import.meta.url).pathname;
const monDir = `${root}engine/pocketmon/crates`;
const pakPath = `${root}dist/sparkwood.monpak`;
const simDir = `${monDir}/pocketmon-sim`;
const eboot = `${monDir}/pocketmon-psp`;
const tape = `${root}apps/mon/tapes/story.tape`;
const goldens = `${root}tests/goldens/mon/story.hashes`;

const argv = Bun.argv.slice(2);
const cmd = argv[0] ?? "check";
const rest = argv.slice(1);

function usage(): never {
  console.error(
    "usage: bun tools/mon.ts <cook|sim|check|record|shots|psp|run> [args…]",
  );
  process.exit(2);
}

/** Cook the content pak. Always runs: content is source. */
async function cook(): Promise<void> {
  mkdirSync(`${root}dist`, { recursive: true });
  await $`bun ${root}apps/mon/cook.ts ${pakPath}`.cwd(root);
}

/** Build the headless simulator and return its binary path. */
async function buildSim(): Promise<string> {
  await $`cargo build --release`.cwd(simDir).quiet();
  return `${simDir}/target/release/pocketmon-sim`;
}

async function main() {
  switch (cmd) {
    case "cook":
      await cook();
      return;

    case "sim": {
      await cook();
      const bin = await buildSim();
      await $`${bin} ${pakPath} ${rest}`;
      return;
    }

    case "check": {
      await cook();
      const bin = await buildSim();
      await $`${bin} ${pakPath} --tape ${tape} --hashes ${goldens} --assert`;
      return;
    }

    case "record": {
      await cook();
      const bin = await buildSim();
      mkdirSync(`${root}tests/goldens/mon`, { recursive: true });
      await $`${bin} ${pakPath} --tape ${tape} --hashes ${goldens}`;
      console.log(
        "\nRecorded. Read the diff before committing: a changed hash is either a" +
          "\nfix or a regression, and the file cannot tell you which.",
      );
      return;
    }

    case "shots": {
      await cook();
      const bin = await buildSim();
      const dir = rest[0] ?? `${root}dist/mon-shots`;
      mkdirSync(dir, { recursive: true });
      await $`${bin} ${pakPath} --tape ${tape} --shots ${dir} --atlas ${dir}`;
      console.log(`\nwrote PNGs to ${dir}`);
      return;
    }

    case "psp":
    case "run": {
      await cook();
      await buildEboot(rest);
      if (cmd === "run") await launchPpsspp();
      return;
    }

    default:
      usage();
  }
}

async function buildEboot(cargoArgs: string[]): Promise<void> {
  let toolchain: ReturnType<typeof resolvePspBuildToolchain>;
  try {
    toolchain = resolvePspBuildToolchain();
  } catch (error) {
    console.error(String((error as Error).message ?? error));
    process.exit(1);
  }
  const sdk = toolchain.sdk.path;

  // cargo-psp reads Psp.toml from its working directory for the PBP metadata.
  const pspToml = `${eboot}/Psp.toml`;
  if (!existsSync(pspToml)) {
    await Bun.write(
      pspToml,
      [
        "# Generated by tools/mon.ts — cargo-psp reads this for the PBP header.",
        '[psp]',
        'title = "SPARKWOOD"',
        "",
      ].join("\n"),
    );
  }

  const rustflags = [
    process.env.RUSTFLAGS ?? "",
    // rust-psp's linker script emits messages cargo would treat as warnings.
    "-A linker-messages",
  ]
    .filter(Boolean)
    .join(" ");

  const env = {
    ...toolchain.environment,
    RUSTFLAGS: rustflags,
    CRATE_CC_NO_DEFAULTS: "1",
    TARGET_CC: "clang",
    TARGET_AR: `${toolchain.llvmBin}/llvm-ar`,
    TARGET_CFLAGS:
      `-target mipsel-sony-psp -mcpu=mips2 -msingle-float -mlittle-endian -mno-abicalls ` +
      `-fno-pic -G0 -mno-check-zero-division -fno-stack-protector ` +
      `-I${sdk}/psp/include -I${sdk}/psp/sdk/include`,
    AR_mipsel_sony_psp: `${toolchain.llvmBin}/llvm-ar`,
    RANLIB_mipsel_sony_psp: `${toolchain.llvmBin}/llvm-ranlib`,
    RUST_PSP_TARGET: `${root}hosts/psp/targets/mipsel-sony-psp.json`,
    RUST_PSP_ABORT_ONLY: "1",
    // opt-level 0 is unusably slow on a 333 MHz console, even in a dev build.
    CARGO_PROFILE_DEV_OPT_LEVEL: process.env.CARGO_PROFILE_DEV_OPT_LEVEL ?? "3",
    // The cooked game, baked in by `include_bytes!`.
    SPARKWOOD_PAK: pakPath,
    // Capture-build inputs (only read under --features capture; set
    // unconditionally so a stale value cannot linger in cargo's fingerprint).
    MON_CAPTURE_INPUT: process.env.MON_CAPTURE_INPUT ?? "",
    MON_CAP_FRAMES: process.env.MON_CAP_FRAMES ?? "",
    MON_CAP_EXIT: process.env.MON_CAP_EXIT ?? "600",
  };

  console.log("pocket mon: cargo psp");
  await $`${toolchain.rustup} run ${toolchain.manifest.rust.toolchain} cargo psp ${cargoArgs}`
    .cwd(eboot)
    .env(env);

  const out = `${eboot}/target/mipsel-sony-psp/debug/EBOOT.PBP`;
  if (existsSync(out)) console.log(`\nEBOOT: ${out}`);
}

async function launchPpsspp(): Promise<void> {
  const candidates = [
    "/Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL",
    "/Applications/PPSSPP.app/Contents/MacOS/PPSSPP",
  ];
  const ppsspp = candidates.find((p) => existsSync(p));
  if (!ppsspp) {
    console.error("PPSSPP not found in /Applications — build only.");
    return;
  }
  const pbp = `${eboot}/target/mipsel-sony-psp/debug/EBOOT.PBP`;
  if (!existsSync(pbp)) {
    console.error(`no EBOOT at ${pbp}`);
    process.exit(1);
  }
  await $`${ppsspp} ${pbp}`;
}

await main();
