// tools/mon.ts — the Pocket Mon command (docs/MON.md).
//
//   bun tools/mon.ts cook             cook apps/mon into dist/sparkwood.monpak
//   bun tools/mon.ts sim [args…]      cook, then run the headless simulator
//   bun tools/mon.ts check            cook + run the story tape against goldens
//   bun tools/mon.ts record           cook + re-record the golden hashes
//   bun tools/mon.ts shots [dir]      cook + write a PNG per checkpoint
//   bun tools/mon.ts audio [dir]      cook + render every song and effect to WAV
//   bun tools/mon.ts psp [cargo args] cook, then build the PSP EBOOT
//   bun tools/mon.ts run              …and launch it in PPSSPP
//   bun tools/mon.ts hw [--debug]     …or load it onto a REAL PSP over PSPLINK
//
// The pak is cooked first by every subcommand on purpose: content lives in
// TypeScript, and a stale pak is the one failure that looks like an engine bug
// (see the repo-wide "stale dist is target-flavored" lesson).

import { $ } from "bun";
import { existsSync, mkdirSync } from "node:fs";
import { createInterface } from "node:readline";
import { createServer } from "node:net";
import { resolvePspBuildToolchain } from "./psp-toolchain.ts";

const root = new URL("..", import.meta.url).pathname;
const monDir = `${root}engine/pocketmon/crates`;
const pakPath = `${root}dist/sparkwood.monpak`;
const simDir = `${monDir}/pocketmon-sim`;
const eboot = `${monDir}/pocketmon-psp`;
const tape = `${root}apps/mon/tapes/story.tape`;
const goldens = `${root}tests/goldens/mon/story.hashes`;

const argv = Bun.argv.slice(2);
const cmd = argv[0] ?? "check";
const rest = argv.slice(1);

function usage(): never {
  console.error(
    "usage: bun tools/mon.ts <cook|sim|check|record|shots|audio|psp|run|hw> [args…]",
  );
  process.exit(2);
}

/** Cook the content pak. Always runs: content is source. */
async function cook(): Promise<void> {
  mkdirSync(`${root}dist`, { recursive: true });
  await $`bun ${root}apps/mon/cook.ts ${pakPath}`.cwd(root);
}

/** Build the headless simulator and return its binary path. */
async function buildSim(): Promise<string> {
  await $`cargo build --release`.cwd(simDir).quiet();
  return `${simDir}/target/release/pocketmon-sim`;
}

async function main() {
  switch (cmd) {
    case "cook":
      await cook();
      return;

    case "sim": {
      await cook();
      const bin = await buildSim();
      await $`${bin} ${pakPath} ${rest}`;
      return;
    }

    case "check": {
      await cook();
      const bin = await buildSim();
      await $`${bin} ${pakPath} --tape ${tape} --hashes ${goldens} --assert`;
      return;
    }

    case "record": {
      await cook();
      const bin = await buildSim();
      mkdirSync(`${root}tests/goldens/mon`, { recursive: true });
      await $`${bin} ${pakPath} --tape ${tape} --hashes ${goldens}`;
      console.log(
        "\nRecorded. Read the diff before committing: a changed hash is either a" +
          "\nfix or a regression, and the file cannot tell you which.",
      );
      return;
    }

    case "shots": {
      await cook();
      const bin = await buildSim();
      const dir = rest[0] ?? `${root}dist/mon-shots`;
      mkdirSync(dir, { recursive: true });
      await $`${bin} ${pakPath} --tape ${tape} --shots ${dir} --atlas ${dir}`;
      console.log(`\nwrote PNGs to ${dir}`);
      return;
    }

    case "audio": {
      await cook();
      const bin = await buildSim();
      const dir = rest[0] ?? `${root}dist/mon-audio`;
      mkdirSync(dir, { recursive: true });
      await $`${bin} ${pakPath} --audio ${dir} --frames 1`;
      console.log(`\nwrote WAVs to ${dir}`);
      return;
    }

    case "psp":
    case "run": {
      await cook();
      await buildEboot(rest);
      if (cmd === "run") await launchPpsspp();
      return;
    }

    case "hw": {
      // Release by default: the debug PRX is 16 MB of symbols against 0.6 MB,
      // and every reload pushes it over USB.
      const debug = rest.includes("--debug");
      await cook();
      await buildEboot(debug ? [] : ["--release"]);
      await runOnHardware(debug ? "debug" : "release");
      return;
    }

    default:
      usage();
  }
}

async function buildEboot(cargoArgs: string[]): Promise<void> {
  let toolchain: ReturnType<typeof resolvePspBuildToolchain>;
  try {
    toolchain = resolvePspBuildToolchain();
  } catch (error) {
    console.error(String((error as Error).message ?? error));
    process.exit(1);
  }
  const sdk = toolchain.sdk.path;

  // cargo-psp reads Psp.toml from its working directory for the PBP metadata.
  const pspToml = `${eboot}/Psp.toml`;
  if (!existsSync(pspToml)) {
    await Bun.write(
      pspToml,
      [
        "# Generated by tools/mon.ts — cargo-psp reads this for the PBP header.",
        '[psp]',
        'title = "SPARKWOOD"',
        "",
      ].join("\n"),
    );
  }

  const rustflags = [
    process.env.RUSTFLAGS ?? "",
    // rust-psp's linker script emits messages cargo would treat as warnings.
    "-A linker-messages",
  ]
    .filter(Boolean)
    .join(" ");

  const env = {
    ...toolchain.environment,
    RUSTFLAGS: rustflags,
    CRATE_CC_NO_DEFAULTS: "1",
    TARGET_CC: "clang",
    TARGET_AR: `${toolchain.llvmBin}/llvm-ar`,
    TARGET_CFLAGS:
      `-target mipsel-sony-psp -mcpu=mips2 -msingle-float -mlittle-endian -mno-abicalls ` +
      `-fno-pic -G0 -mno-check-zero-division -fno-stack-protector ` +
      `-I${sdk}/psp/include -I${sdk}/psp/sdk/include`,
    AR_mipsel_sony_psp: `${toolchain.llvmBin}/llvm-ar`,
    RANLIB_mipsel_sony_psp: `${toolchain.llvmBin}/llvm-ranlib`,
    RUST_PSP_TARGET: `${root}hosts/psp/targets/mipsel-sony-psp.json`,
    RUST_PSP_ABORT_ONLY: "1",
    // opt-level 0 is unusably slow on a 333 MHz console, even in a dev build.
    CARGO_PROFILE_DEV_OPT_LEVEL: process.env.CARGO_PROFILE_DEV_OPT_LEVEL ?? "3",
    // The cooked game, baked in by `include_bytes!`.
    SPARKWOOD_PAK: pakPath,
    // Capture-build inputs (only read under --features capture; set
    // unconditionally so a stale value cannot linger in cargo's fingerprint).
    MON_CAPTURE_INPUT: process.env.MON_CAPTURE_INPUT ?? "",
    MON_CAP_FRAMES: process.env.MON_CAP_FRAMES ?? "",
    MON_CAP_EXIT: process.env.MON_CAP_EXIT ?? "600",
  };

  console.log("pocket mon: cargo psp");
  await $`${toolchain.rustup} run ${toolchain.manifest.rust.toolchain} cargo psp ${cargoArgs}`
    .cwd(eboot)
    .env(env);

  const profile = cargoArgs.includes("--release") ? "release" : "debug";
  const out = `${eboot}/target/mipsel-sony-psp/${profile}/EBOOT.PBP`;
  if (existsSync(out)) console.log(`\nEBOOT: ${out}`);
}

// ---------------------------------------------------------------------------
// Real hardware, over PSPLINK
// ---------------------------------------------------------------------------

/**
 * Serve the build directory as `host0:` over USB and `ldstart` the PRX, then
 * sit in a rebuild/reload loop.
 *
 * Same shape as tools/hw.ts (which does this for the 2D runtime); kept here
 * rather than generalised because the two differ in every path and neither is
 * complicated.
 */
async function runOnHardware(profile: string): Promise<void> {
  const usbhostfs = Bun.which("usbhostfs_pc");
  const pspsh = Bun.which("pspsh");
  if (!usbhostfs || !pspsh) {
    console.error(
      "PSPLINK host tools not on PATH (need usbhostfs_pc and pspsh).\n" +
        "  brew install pspdev/pspdev/pspsdk   # or build psplink from source",
    );
    process.exit(1);
  }

  const targetDir = `${eboot}/target/mipsel-sony-psp/${profile}`;
  const prx = `${targetDir}/pocketmon-psp.prx`;
  if (!existsSync(prx)) {
    console.error(`no PRX at ${prx}`);
    process.exit(1);
  }

  const basePort = await findBasePort(Number(process.env.PSP_HW_PORT ?? 10300));
  const running = (await $`pgrep -x usbhostfs_pc`.nothrow().text()).trim();
  if (running) {
    console.log(
      `note: another usbhostfs_pc is running (pid ${running.split("\n").join(", ")}).\n` +
        "      Only one can own the PSP's USB — kill it if this link does not connect.",
    );
  }

  console.log(`serving ${profile} build as host0: on port ${basePort}`);
  const server = Bun.spawn([usbhostfs, "-b", String(basePort), targetDir], {
    stdout: "pipe",
    stderr: "pipe",
  });

  // usbhostfs_pc announces every (re)connection; counting them is how we know
  // a reset actually came back rather than hanging.
  let connects = 0;
  const pump = async (stream: ReadableStream<Uint8Array>) => {
    const dec = new TextDecoder();
    for await (const chunk of stream) {
      for (const _ of dec.decode(chunk).matchAll(/Connected to device/g)) connects++;
    }
  };
  void pump(server.stdout);
  void pump(server.stderr);

  const stop = () => {
    try {
      server.kill();
      process.kill(server.pid, "SIGKILL");
    } catch {
      // already gone
    }
  };
  process.on("SIGINT", () => {
    stop();
    process.exit(0);
  });

  const waitForConnect = async (from: number, timeoutMs: number): Promise<boolean> => {
    const t0 = Date.now();
    while (connects <= from) {
      if (Date.now() - t0 > timeoutMs) return false;
      await Bun.sleep(200);
    }
    return true;
  };

  const sh = async (command: string, timeoutMs = 10_000): Promise<string> => {
    const child = Bun.spawn([pspsh, "-p", String(basePort), "-e", command], {
      stdout: "pipe",
      stderr: "pipe",
    });
    const timer = setTimeout(() => child.kill(), timeoutMs);
    const [out, err] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);
    clearTimeout(timer);
    return (out + err).trim();
  };

  console.log("waiting for the PSP — launch PSPLINK on it (XMB -> Game -> PSPLINK).");
  if (!(await waitForConnect(0, 120_000))) {
    console.error("PSP never connected. Check the USB DATA cable and that PSPLINK is running.");
    stop();
    process.exit(1);
  }
  console.log("PSP connected.");

  const load = async (): Promise<void> => {
    const before = connects;
    process.stdout.write("resetting PSPLINK... ");
    await sh("reset", 6000);
    console.log((await waitForConnect(before, 15_000)) ? "connected." : "no reconnect; continuing.");
    const out = await sh("ldstart host0:/pocketmon-psp.prx");
    console.log("  " + (out || "(no output)"));
    if (/Failed|Error/i.test(out)) {
      console.log("  load failed — is PSPLINK still running and host0: mounted?");
    }
  };

  await load();
  console.log("\n[mon:hw] Enter = rebuild + reload   |   q + Enter = quit\n");
  const rl = createInterface({ input: process.stdin });
  for await (const line of rl) {
    const cmd = line.trim().toLowerCase();
    if (cmd === "q" || cmd === "quit" || cmd === "exit") break;
    await cook();
    await buildEboot(profile === "release" ? ["--release"] : []);
    await load();
    console.log("\n[mon:hw] Enter = rebuild + reload   |   q + Enter = quit\n");
  }
  rl.close();
  stop();
}

/** A block of consecutive free ports for the PSPLINK link. */
async function findBasePort(start: number): Promise<number> {
  const free = (port: number) =>
    new Promise<boolean>((resolve) => {
      const srv = createServer();
      srv.once("error", () => resolve(false));
      srv.once("listening", () => srv.close(() => resolve(true)));
      srv.listen(port, "127.0.0.1");
    });
  for (let base = start; base <= start + 3000; base += 100) {
    let ok = true;
    for (let i = 0; i <= 8; i++) {
      if (!(await free(base + i))) {
        ok = false;
        break;
      }
    }
    if (ok) return base;
  }
  throw new Error("no free TCP port block for the PSPLINK link");
}

async function launchPpsspp(): Promise<void> {
  const candidates = [
    "/Applications/PPSSPPSDL.app/Contents/MacOS/PPSSPPSDL",
    "/Applications/PPSSPP.app/Contents/MacOS/PPSSPP",
  ];
  const ppsspp = candidates.find((p) => existsSync(p));
  if (!ppsspp) {
    console.error("PPSSPP not found in /Applications — build only.");
    return;
  }
  const pbp = `${eboot}/target/mipsel-sony-psp/debug/EBOOT.PBP`;
  if (!existsSync(pbp)) {
    console.error(`no EBOOT at ${pbp}`);
    process.exit(1);
  }
  await $`${ppsspp} ${pbp}`;
}

await main();
